### ISSUE TITLE
FIFO sizing bug in trng_csprng_fifo.v

### ISSUE THREAD

**Issue by joshuisken** [secworks/trng#1]
In file trng_csprng_fifo.v the parameter FIFO_MAX is computed wrong (courtesy Dhana Shree Boopathy)

Line 60 in file trng_csprng_fifo.v:
  localparam FIFO_MAX       = (2 >> FIFO_ADDR_BITS) - 1;

Needs to be replaced by:
  localparam FIFO_MAX       = (1 << FIFO_ADDR_BITS) - 1;

**Comment by secworks** [comment]
That is very true. How sloppy of me. Thanks to you and Dhana Shree Boopathy.

This is fixed in commit: https://github.com/secworks/trng/commit/754a0a6112e0f20b5d77ae6c0d1bdbf9f618590e
