### ISSUE TITLE
tb_trng testbench error

### ISSUE THREAD

**Issue by ohdonghak** [secworks/trng#2]
Hi!
We are conducting test simulation using tb_trng.
![image](https://user-images.githubusercontent.com/54651774/110719010-7280c100-824f-11eb-9e91-b0d96d3968fd.png)

But there was a stop in the middle like above. Why do you know that?

**Comment by ohdonghak** [comment]
Now I'm using a fake_module. the test went through when the enable of rosc_entropy and avalanche_entropy was set to zero. If the enable of rosc_entropy and avalanche_entropy is set to 1, why can not it be operated?
Is there anything that needs to be handled separately during the operation?

**Comment by ohdonghak** [comment]
@secworks Can you confirm that?

**Comment by ohdonghak** [comment]
Hello, secworks.
There was a section where infinite loops occurred in the union circuit. I solved this issue through the simulation option -delay_trigger.

**Comment by secworks** [comment]
Aloha!
Sorry for a late response. If you set avalanche entropy to one, it will expect that the avalanche entropy source is present. This will not be true in a simulation environment. The simulation is really just to check that the syntax is borked. The trng will not produce any meaningful results in a sim environment.
